// =====================================================
// FILE: Models/TinyUrlModels.cs
// PURPOSE: Defines the data structures used in the app
// DESIGN PATTERN: DTO Pattern (Data Transfer Object)
// SOLID: Single Responsibility - each class has one job
// =====================================================

namespace TinyUrl.Api.Models
{
    // -------------------------------------------------------
    // This class represents ONE row in the database table.
    // It stores everything about a shortened URL.
    // -------------------------------------------------------
    public class TinyUrlEntry
    {
        // Unique ID - auto generated by database 
        public int Id { get; set; }

        // The 6-character short code e.g. "aB3xKq"
        public string Code { get; set; } = string.Empty;

        // The original long URL the user submitted
        // e.g. "https://www.google.com"
        public string OriginalUrl { get; set; } = string.Empty;

        // If true, this URL won't appear in the public list
        public bool IsPrivate { get; set; }

        // How many times this short URL was visited/clicked
        public int Clicks { get; set; }

        // When this short URL was created
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    }

    // -------------------------------------------------------
    // DTO = Data Transfer Object
    // This is what the CLIENT SENDS when creating a short URL.      
    //
    // SOLID: Interface Segregation Principle
    //  Client only sees fields it actually needs to send
    // -------------------------------------------------------
    public class TinyUrlAddDto
    {
        // The long URL the user wants to shorten
        public string Url { get; set; } = string.Empty;

        // Whether to hide this URL from the public list
        public bool IsPrivate { get; set; }
    }

    // -------------------------------------------------------
    // DTO for UPDATING an existing short URL
    // Client can only change the URL and Private status
    // They cannot change Id, Code, Clicks, CreatedAt
    // -------------------------------------------------------
    public class TinyUrlUpdateDto
    {
        // New URL to replace the existing one
        public string Url { get; set; } = string.Empty;

        // Update private/public status
        public bool IsPrivate { get; set; }
    }
}